name = "webls"
version = "1.6.1"

description = "A simple web utility library for RSS feeds, Sitemaps, Robots.txt, etc."
licences = ["Apache-2.0"]
repository = { type = "github", user = "versecafe", repo = "webls" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_time = ">= 1.6.0 and < 2.0.0"
parsed_it = { path = "../parsed_it" }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.3.2 and < 3.0.0"
